---
###
### DEFAULT PIPELINE
###

kind: pipeline
name: default

trigger:
  event: [push]
  branch: [master]

steps:
  - name: build
    image: plugins/docker
    settings:
      username: { from_secret: quay_username }
      password: { from_secret: quay_password }
      registry: quay.io
      repo: quay.io/zebbra/node-red
      tags: 'latest,${DRONE_COMMIT_SHA:0:7}'
      cache_from:
        - quay.io/zebbra/node-red:latest
      custom_labels: [quay.expires-after=30d]
      mtu: 1376
