---
kind: pipeline
type: kubernetes
name: release

trigger:
  event: [push]
  branch: [master]

steps:
  - name: build
    image: plugins/docker
    settings:
      username: { from_secret: quay_username }
      password: { from_secret: quay_password }
      registry: quay.io
      repo: quay.io/zebbra/node-red
      tags: "latest,git-${DRONE_COMMIT_SHA:0:7}"
      cache_from:
        - quay.io/zebbra/node-red:latest
      mtu: 1300

  - name: deploy
    image: pelotech/drone-helm3
    settings:
      kube_api_server: https://kubernetes.default
      kube_token: { from_secret: kubernetes_token }
      kube_certificate: { from_secret: kubernetes_certificate }
      add_repos:
        - k8s-at-home=https://k8s-at-home.com/charts/
      chart: k8s-at-home/node-red
      release: node-red
      namespace: zebbra
      values_files: [./deploy/values.yaml]
      values: image.tag=git-${DRONE_COMMIT_SHA:0:7}
