version: "3.7"

services:
  node-red:
    image: quay.io/zebbra/node-red:latest
    build: .
    environment:
      - TZ=Europe/Zurich
    ports:
      - "1880:1880"
    volumes:
      - ./data:/data
