apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-red
spec:
  selector:
    matchLabels:
      app: node-red
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: node-red
    spec:
      restartPolicy: Always
      containers:
      - name: node-red
        image: quay.io/zebbra/node-red:latest
        imagePullPolicy: Always
        env: []
        ports:
        - containerPort: 1880
          protocol: TCP
          name: http
        volumeMounts:
        - name: node-red-data
          mountPath: /data
      securityContext:
        fsGroup: 1001
      volumes:
        - name: node-red-data
          persistentVolumeClaim:
            claimName: node-red-data
